# Generated by Django 4.0.5 on 2022-06-15 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('major', models.CharField(max_length=100)),
                ('date_work', models.DateField(max_length=100)),
                ('salary', models.FloatField(max_length=50)),
                ('boss', models.CharField(choices=[('A', 'Alex'), ('B', 'Bob'), ('C', 'Cole'), ('D', 'Dany'), ('E', 'Elen')], default='A', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
