# Generated by Django 4.0.5 on 2022-06-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='boss',
            field=models.CharField(choices=[('A', 'Alex'), ('B', 'Bob'), ('C', 'Cole'), ('D', 'Dany'), ('E', 'Elen')], max_length=1),
        ),
    ]
