# Generated by Django 4.0.5 on 2022-06-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_worker_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='boss',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_work',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
