# Generated by Django 4.0.5 on 2022-06-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_worker_boss_alter_worker_date_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='owner',
        ),
    ]
