# Generated by Django 4.0.5 on 2022-06-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_worker_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='boss',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_work',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.FloatField(blank=True, max_length=50, verbose_name='salary($)'),
        ),
    ]
