# Generated by Django 4.0.5 on 2022-06-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_worker_boss_alter_worker_date_work_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='boss',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.boss'),
        ),
    ]
