# Generated by Django 4.0.5 on 2022-06-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_boss_alter_worker_name_alter_worker_boss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='date_work',
            new_name='work_date',
        ),
    ]
